<?php
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');
$group_helper = new Property_View_Helper_PropertyGroup();
?>
<script type="text/javascript">
$(document).ready(function() {
	floatingbar('#floatingbar',"#button_top_bar",null);
	/****************************Sorting Table Start*********************/
	var oTable = $("#sortTable").dataTable({
				"bPaginate": false,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,
				"aaSorting": [[ 1, "asc" ]],				
				"aoColumnDefs": [ 
						{ "bSortable": false, "bSortClasses": false,  "aTargets": [ 0 ] }
					],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			}); 	
	
	$('td', oTable.fnGetNodes()).hover( function() {		
		$(this).parents("tr:first").children('td').addClass( 'highlighted' );
	}, function() {
		$('td.highlighted').removeClass('highlighted');
	} );
	
	/* Get the rows which are currently selected */
	function fnGetSelected( oTableLocal )
	{
		var aReturn = new Array();
		var aTrs = oTableLocal.fnGetNodes();
		
		for ( var i=0 ; i<aTrs.length ; i++ )
		{
			if ( $(aTrs[i]).hasClass('row_selected') )
			{
				aReturn.push( aTrs[i] );
			}
		}
		return aReturn;
	}
	
	/****************************Sorting Table End*********************/
	
		function openMsgDialog(msg)
		{
			$('#dialog_container').html(msg).dialog({
						autoOpen: true,
						modal: false,
						show: 'fade',
						resizable: 'false',				
						buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
						open: function(event, ui)
							 {
								setTimeout(function() 
								{									
									if($('#' + event.target.id).dialog('isOpen'))
									{
										$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
									}
								}, 10000);
							  }
					});
		}
		
		function deleteThis(self)
		{
			var arr = $(self).attr('rel').split('_');
			$.ajax({
				 url: "<?php echo $this->url( array('module'=> 'Property', 'controller' => 'backendgrp', 'action'     => 'deletegrp' ), 'adminrout',    true) ?>",
				 type: 'POST',
				 data: { id: arr[0], property_name: arr[1] },
				 beforeSend: function(){
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
					 },
				 success: function(response) 
				 {
					//alert(response);
					var json_arr = eval("("+response+")");
					if(json_arr.status == 'ok')
					{
						$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").addClass('row_selected');
						var oTables = $('#sortTable').dataTable();
						var anSelected = fnGetSelected( oTables );
						oTables.fnDeleteRow( anSelected[0] );
					}
					else
					{
						openMsgDialog(json_arr.msg);
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator("common_delete_title"); ?>" alt=="<?php echo $this->translator->translator("common_delete_title"); ?>" border="0" />');
					}
				 },
				error: function(xhr, status, error){
					var msg = "Error! " + xhr.status + " " + error;
					openMsgDialog(msg);
				}
			});
		}
		
		function deleteAll(self)
		{
			var id_str = '';
			for(var i=0;i < $('input.check_btn:checked').length;i++)
			{
				if(i == 0)
				{
					 id_str += $('input.check_btn:checked:eq('+i+')').val();
				}
				else
				{
					id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
				}
			}
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Property', 'controller' => 'backendgrp', 'action'     => 'deleteallgrp' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id_st: id_str},
					beforeSend: function(){
						$(self).html('<span class="icon loader"></span>');
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							for(var i= ($('input.check_btn:checked').length-1);i >= 0;i--)
							{	
								if(!checkNonDeletedId($('input.check_btn:checked:eq('+i+')').val(),json_arr.non_del_arr))
								{							
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").addClass('row_selected');									
								}
							}
							var oTabled = $('#sortTable').dataTable();
							var anSelected = fnGetSelected( oTabled );
							for(var k = 0; k < anSelected.length; k++)
							{
								oTabled.fnDeleteRow( anSelected[k] );
							}
						}
						else
						{							
							openMsgDialog(json_arr.msg);
						}	
						$(self).html('<span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span>');
					},
					error: function(xhr, status, error){
						var msg = "Error! " + xhr.status + " " + error;
						openMsgDialog(msg);
					}
			});	
		}
	
	$('a.delete_btn').click(function() {
		var self = this;
		$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('property_list_delete_confirm')); ?>").dialog({
			resizable: false,
			width:400,
			height:170,
			modal: true,
			show: 'fade',
			hide: 'explode',
			buttons: {
					'<?php echo html_entity_decode($this->translator->translator("property_delete"), ENT_QUOTES, "UTF-8"); ?>': function() {
					deleteThis(self);
					$(this).dialog('close');
				},
			'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
					$(this).dialog('close');
				}
			}
		});
		
	});
	
	$('a.publish_btn').click(function() {
		var self = this;
		<?php if ($this->allow('publishgrp','backendgrp','Property')){ ?>			
			var arr = $(self).attr('rel').split('_');		
			$.ajax({
				 url: "<?php echo $this->url( array('module'=> 'Property', 'controller' => 'backendgrp', 'action'     => 'publishgrp' ), 'adminrout',    true) ?>",
				 type: 'POST',
				 data: { id: arr[0], property_name: arr[1], paction: arr[2]},
				 beforeSend: function(){
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" border="0" height="17" />');
					 },
				 success: function(response) 
				 {
					//alert(response);
					var json_arr = eval("("+response+")");
					if(json_arr.status == 'ok')
					{
						if(json_arr.active == '1')
						{
							$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/published.gif" border="0" title="<?php echo $this->translator->translator("common_unpublish_title"); ?>" alt="<?php echo $this->translator->translator("common_unpublish_title"); ?>" />').attr('rel',arr[0]+"_"+arr[1]+"_unpublish");
						}
						else
						{
							$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif" border="0" title="<?php echo $this->translator->translator("common_publish_title"); ?>" alt="<?php echo $this->translator->translator("common_publish_title"); ?>" />').attr('rel',arr[0]+"_"+arr[1]+"_publish");
						}
					}
					else
					{
						openMsgDialog(json_arr.msg);
					}
				 },
				error: function(xhr, status, error){
					var msg = "Error! " + xhr.status + " " + error;
					openMsgDialog(msg);
				}
			});
		<?php }else{ ?>
			var msg = "<?php echo $this->translator->translator('common_publish_perm'); ?>";
				openMsgDialog(msg);
		<?php } ?>
	});
	
		
	$('a.publish_all').click(function() {
		var self = this;
		<?php if ($this->allow('publishgrp','backendgrp','Property')){ ?>
			var bigrel = $(self).attr('rel');
			if($('input.check_btn:checked').length > 0)
			{
				var id_str = '';
				for(var i=0;i < $('input.check_btn:checked').length;i++)
				{
					if(i == 0)
					{
						 id_str += $('input.check_btn:checked:eq('+i+')').val();
					}
					else
					{
						id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
					}
				}
				
				$.ajax({
						url: "<?php echo $this->url( array('module'=> 'Property', 'controller' => 'backendgrp', 'action'     => 'publishallgrp' ), 'adminrout',    true) ?>",
						type: 'POST',
						data: { id_st: id_str, paction: bigrel},
						beforeSend: function(){
							$(self).html('<span class="icon loader"></span>');
						 },
						success: function(response) 
						{
							//alert(response);
							var json_arr = eval("("+response+")");
							if(json_arr.status == 'ok')
							{
								if(bigrel=='publish')
								{	
									for(var i=0;i < $('input.check_btn:checked').length;i++)
									{	
										var rel = $('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").children("a:nth-child(1)").attr('rel');
										var rel_arr = rel.split('_');
										var new_rel = rel_arr[0]+'_'+rel_arr[1]+'_unpublish';
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").children("a:nth-child(1)").attr('rel',new_rel);
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").children("a:nth-child(1)").html('<img src="application/modules/Administrator/layouts/scripts/images/tools/published.gif" border="0" title="<?php echo $this->translator->translator("common_unpublish_title"); ?>" alt="<?php echo $this->translator->translator("common_unpublish_title"); ?>" />');								
									}
								}
								else
								{
									for(var i=0;i < $('input.check_btn:checked').length;i++)
									{
										var rel = $('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").children("a:nth-child(1)").attr('rel');
										var rel_arr = rel.split('_');
										var new_rel = rel_arr[0]+'_'+rel_arr[1]+'_publish';
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").children("a:nth-child(1)").attr('rel',new_rel);
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").children("a:nth-child(1)").html('<img src="application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif" border="0" title="<?php echo $this->translator->translator("common_publish_title"); ?>" alt="<?php echo $this->translator->translator("common_publish_title"); ?>" />');								
									}
								}
	
							}
							else
							{
								openMsgDialog(json_arr.msg);
							}
							if(bigrel=='publish')
							{	
								$(self).html('<span class="icon publish"><?php echo addslashes($this->translator->translator("common_publish_selected")); ?></span>');
							}
							else
							{
								$(self).html('<span class="icon unpublish"><?php echo addslashes($this->translator->translator("common_unpublish_selected")); ?></span>');
							}
						},
						error: function(xhr, status, error){
							var msg = "Error! " + xhr.status + " " + error;
							openMsgDialog(msg);
						}
				});			
			}
			else
			{
				var msg = "<?php echo $this->translator->translator('property_group_selected_err'); ?>";
				openMsgDialog(msg);
			}
		<?php }else{ ?>
			var msg = "<?php echo $this->translator->translator('common_publish_perm'); ?>";
				openMsgDialog(msg);
		<?php } ?>
	});
		
	$('a.delete_all').click(function() {
		var self = this;
		if($('input.check_btn:checked').length > 0)
		{
			$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('property_list_delete_confirm')); ?>").dialog({
					resizable: false,
					width:400,
					height:170,
					modal: true,
					show: 'fade',
					hide: 'explode',
					buttons: {
							'<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>': function() {
							deleteAll(self);
							$(this).dialog('close');
						},
					'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
							$(this).dialog('close');
						}
					}
				});		
		}
		else
		{
			var msg = "<?php echo $this->translator->translator('property_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
	
	$('input.checkAll_btn').click(function() {
		var self = this;
		if($(self).is(':checked'))
		{		
			$('input.check_btn').attr('checked', true);
		}
		else
		{
			$('input.check_btn').attr('checked', false);
		}
	});
	
	function checkNonDeletedId(id,id_arr)
	{
		var tmp = false;
		for(var i = 0;i < id_arr.length;i++)
		{
			if(id_arr[i] == id)
			{
				tmp = true;
				break;
			}
		}
		return tmp;
	}
	
});
</script>

<div id="container">
<?php if (!$this->allow('listgrp')) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="property-group"><h1><?php echo $this->translator->translator('property_group_list'); ?></h1></div>
    
    <div class="button-container">
        <?php if ($this->allow('addgrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Property','controller'=>'Backendgrp', 'action'=>'addgrp'),'adminrout',true);?>"><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        
        <?php if ($this->allow('publishgrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="publish"><span class="icon publish"><?php echo $this->translator->translator('common_publish_selected'); ?></span></a></span>
        <?php endif; ?>
        
        <?php if ($this->allow('publishgrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="unpublish"><span class="icon unpublish"><?php echo $this->translator->translator('common_unpublish_selected'); ?></span></a></span>
        <?php endif; ?>
        
        <?php  if ($this->allow('deletegrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo $this->translator->translator('common_delete_selected'); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<div id="button_top_bar"></div>
<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('nav_menu.phtml');  ?>
    </div>
    
    	
    <div id="content-inner">
    	<div class="pagination">
    		<?php echo $this->paginationControl($this->property_group_datas, 'Sliding', 'top_pagination.phtml'); ?>
        </div>
        
        <div class="chart">
        	<div class="data-table">
        		<table id="sortTable" width="100%" align="center" cellpadding="0" cellspacing="0">
                	<thead>
                    	<tr>
                 			<th width="4%" class="center"><input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn" /></th>
                 			<th width="4%"><?php echo $this->translator->translator('property_id'); ?></th>
                  			<th width="24%"><?php echo $this->translator->translator('property_group_name'); ?></th>
                            <th width="24%"><?php echo $this->translator->translator('common_entry_by'); ?></th>
                   			<th width="20%"><?php echo $this->translator->translator('property_number_sub_element'); ?></th>
                  			<th width="9%"><?php echo $this->translator->translator('property_status'); ?></th>
                            <th width="15%"><?php echo $this->translator->translator('property_action'); ?></th>
                		</tr>
                	</thead>
                    <tbody>
                    <?php
                    $mem_db = new Members_Model_DbTable_MemberList();  
                    $j = 1;
                    foreach ($this->property_group_datas as $entry): 
                        if($j % 2 == 0)
                        {
                            $onmouseout = "this.bgColor='#FFFFFF';";
                            $background = '#FFFFFF';
                        }
                        else
                        {
                            $onmouseout = "this.bgColor='#F7F7F7';";
                            $background = '#F7F7F7';
                        }
                    ?>
                   		<tr bgcolor="<?php echo $background; ?>" onmouseover="this.bgColor='#FCF5DD';" onmouseout="<?php echo $onmouseout; ?>">
                     		<td class="center checkbox"><input type="checkbox" name="checkbtn" id="checkbtn" value="<?php echo $this->escape($entry->id); ?>" class="check_btn" /></td>
                      		<td class="center"><?php echo $this->escape($entry->id); ?></td>
                      		<td>
								<?php
                                $num_cat = $group_helper->getNumOfProperty($this->escape($entry->id));
                                $num_product = $group_helper->getNumOfProduct($this->escape($entry->id));
                                $num_type = $group_helper->getNumOfPropertyType($this->escape($entry->id));
                                $link_url_cat = $this->url(array('module' => 'Property', 'controller' => 'backend', 'action' => 'list', 'group_id' => $entry->id),'adminrout',true) ;
                                $link_url_pro = $this->url(array('module' => 'Property', 'controller' => 'Backendpro', 'action' => 'list', 'group_id' => $entry->id),'adminrout',true);
                                $link_url_type = $this->url(array('module' => 'Property', 'controller' => 'Backendtype', 'action' => 'list', 'group_id' => $entry->id),'adminrout',true);
                              	?>
                            	<?php echo $this->escape($entry->property_name); ?>
                      		</td>
                     		<td>
								<?php 
                        		$member_info = $mem_db->getMemberInfo($this->escape($entry->entry_by));
                        		echo $this->escape($member_info['username']); ?>
                          	</td>
                      		<td class="center">
                      		<?php 												  	
                            	echo '<span class="spacer"><a href="'.$link_url_cat.'"><img src="application/modules/Administrator/layouts/scripts/images/tools/cat-view.gif" class="myTooltip" title="'.$this->translator->translator('category_language').' ('.$this->escape($num_cat).')'.'" alt="'.$this->translator->translator('category_language').' ('.$this->escape($num_cat).')'.'"  /></a></span>';
                        
                            	echo '<span class="spacer"><a href="'.$link_url_pro.'"><img src="application/modules/Administrator/layouts/scripts/images/tools/property/property.png" class="myTooltip" title="'.$this->translator->translator('page_language').' ('.$this->escape($num_product).')'.'" alt="'.$this->translator->translator('page_language').' ('.$this->escape($num_product).')'.'"  /></a></span>';
                        
                            	echo '<span><a href="'.$link_url_type.'"><img src="application/modules/Administrator/layouts/scripts/images/tools/business-type.png" class="myTooltip" title="'.$this->translator->translator('type_language').' ('.$this->escape($num_type).')'.'" alt="'.$this->translator->translator('type_language').' ('.$this->escape($num_type).')'.'"  /></a></span>';
                        	?>
                      		</td>
                     
                      		<td class="center"><a href="javascript:void(0);" class="publish_btn" rel="<?php echo $this->escape($entry->id); ?>_<?php echo $this->escape($entry->property_name); ?>_<?php if($this->escape($entry->active) == '1'){ ?>unpublish<?php }else{ ?>publish<?php } ?>"><?php if($this->escape($entry->active) == '1'){ ?><img src="application/modules/Administrator/layouts/scripts/images/tools/published.gif" border="0" title="<?php echo $this->translator->translator('common_unpublish_title'); ?>" alt="<?php echo $this->translator->translator('common_unpublish_title'); ?>" /><?php }else{ ?><img src="application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif" border="0" title="<?php echo $this->translator->translator('common_publish_title'); ?>" alt="<?php echo $this->translator->translator('common_publish_title'); ?>" /><?php } ?></a></td>
                      
                      		<td class="tools-list">
                            	<ul>
                                	<li>
                                    <?php if ($this->allow('editgrp','backendgrp','Property')) : ?>
                                	<a href="<?php echo $this->url( array('module'=> 'Property', 'controller' => 'backendgrp', 'action'     => 'editgrp', 'id' => $this->escape($entry->id) ), 'adminrout',    true) ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/setting.png" title="<?php echo $this->translator->translator('common_setting_title'); ?>" alt="<?php echo $this->translator->translator('common_setting_title'); ?>" border="0" /></a>
                                	<?php endif; ?>
                                    </li>
                                    
                                    <li>
                                    <?php if ($this->allow('update','search','Settings')) : ?>
                                	<a href="<?php echo $this->url( array('module'=> 'Settings', 'controller' => 'search', 'action'     => 'update', 'group_id' => $this->escape($entry->id), 'group_form_id_field' => 'dynamic_form', 'group_table' => 'property_group', 'static_table' => 'property_page', 'back_module_name' => 'Property', 'back_controller_name' => 'backendgrp', 'back_action_name' => 'listgrp' ), 'adminrout', true) ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/search-settings.png" title="<?php echo $this->translator->translator('common_set_search_title'); ?>" alt="<?php echo $this->translator->translator('common_set_search_title'); ?>" border="0" /></a>
                                	<?php endif; ?>
                                    </li>
                                    
                                    <li>
                                    <?php if ($this->allow('deletegrp','backendgrp','Property')) : ?>
                                	<a href="javascript:void(0);" class="delete_btn"  rel="<?php echo $this->escape($entry->id); ?>_<?php echo $this->escape($entry->property_name); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator('common_delete_title'); ?>" border="0" /></a>
                                	<?php endif; ?>
                                    </li>
                                </ul>
                        	</td>
                    	</tr>
                    <?php 													
                        $j++;
                        endforeach;	
                   	?>
                   </tbody>
				</table>
			</div>
		</div>
        
        <div class="pagination">
    		<?php echo $this->paginationControl($this->property_group_datas, 'Sliding', 'pagination.phtml'); ?>
        </div>
        
	</div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('property_group_list'); ?></h1>
    
    <div class="button-container">
        <?php if ($this->allow('addgrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Property','controller'=>'Backendgrp', 'action'=>'addgrp'),'adminrout',true);?>"><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        
        <?php if ($this->allow('publishgrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="publish"><span class="icon publish"><?php echo $this->translator->translator('common_publish_selected'); ?></span></a></span>
        <?php endif; ?>
        
        <?php if ($this->allow('publishgrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="unpublish"><span class="icon unpublish"><?php echo $this->translator->translator('common_unpublish_selected'); ?></span></a></span>
        <?php endif; ?>
        
        <?php  if ($this->allow('deletegrp','backendgrp','Property')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo $this->translator->translator('common_delete_selected'); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>

<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('property_group_list')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>	
</div>