<?php
$version = Zend_Registry::get('version');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');
?>

<script type="text/javascript">
$(document).ready(function() {	
	floatingbar('#floatingbar',"#button_top_bar",null);
	/****************************Sorting Table Start*********************/
	var oTable = $("#sortTable").dataTable({
				"bPaginate": false,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,
				"aaSorting": [[ 1, "asc" ]],				
				"aoColumnDefs": [ 
						{ "bSortable": false, "bSortClasses": false,  "aTargets": [ 0 ] }
					],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			}); 	
	
	$('td', oTable.fnGetNodes()).hover( function() {		
		$(this).parents("tr:first").children('td').addClass( 'highlighted' );
	}, function() {
		$('td.highlighted').removeClass('highlighted');
	} );
	
	lastClassAdd(oTable);
	/****************************Sorting Table End*********************/		
		
		$('a.reset_btn').click(function() {			
			 resetFields();	
			 removeError();	
		});
		
		function resetFields()
		{
			$( "#formFormat" )[ 0 ].reset();
		}
		
		function removeError()
		{
			$('#actionMessage').html('');
						
			$.each($('form').serializeArray(), function(i, field) {				
					$('#'+field.name).removeClass('ui-state-error');
					$('#'+field.name+'_err').html('');									
			});				
		}
		
		function addError(key,errMsg)
		{
			var err_id = key+'_err';
			var field_name = key;
			$('#'+field_name).addClass('ui-state-error');
			$('#'+err_id).append(errMsg);
		}
		
		function openLoaderDialog()
		{
			$('#dialog_loader').dialog({
						autoOpen: true,
						modal: true,
						show: 'fade',
						resizable: 'false',				
						open: function(event, ui)
							 {
								$("#progressbar").progressbar({
									value:100
					
								});							
							  }
					});
		}
		
		function closeLoaderDialog()
		{
			$('#dialog_loader').dialog('option','hide','explode').dialog('close');
		}
		
		function getFormData()
		{
			var fieldObj = {};
			$.each($('#formFormat').serializeArray(), function(i, field) {			
								
				fieldObj[field.name] = field.value;			
										
			});
			return fieldObj;
		}
		
		$("#add-format-form").dialog({
			autoOpen: false,
			width: 900,
			//height: 400,
			show: 'fade',			
			modal: true
		});	
		
		$('a.add_new_dialog_btn').click(function() {
				resetFields();
			 	removeError();	
				$('#add-format-form').dialog('open');				
		});
		
		$('a.close_dialog_btn').click(function() {			
			 resetFields();
			 removeError();	
			 $("#add-format-form").dialog('option','hide','explode').dialog('close');		
		});
		
		$('a.add_variable_btn').click(function() 
		{	
			var formData = getFormData();		
					
			$.ajax({
				url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'formats', 'action'     => 'add' ), 'adminrout',    true) ?>",
					type: 'POST',
					data: formData,
					beforeSend: function(){						
						removeError();
						openLoaderDialog();					
					 },
					success: function(response){
						//alert(response);					
						var json_arr = eval("("+response+")");					
						closeLoaderDialog();					
						if(json_arr.status == 'ok')
						{
							generateNewRow(json_arr.datas, oTable);							
							$('#actionMessage').html(succMsgDesign(json_arr.msg));	
							resetFields();												
						}
						else if(json_arr.status == 'errV')
						{
							$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
													
							for(var i= 0; i < json_arr.msg.length; i++)
							{
								addError(json_arr.msg[i].key,json_arr.msg[i].value);							
							}
						}
						else
						{
							$('#actionMessage').html(errMsgDesign(json_arr.msg));
						}
					}
			});
		});
		
		allFunctions();
		
});

function generateNewRow(datas, oTable)
{	
	var row =	'<ul>'+
					'<li>'+
							<?php if ($this->allow('edit','formats','Newsletter')) : ?>
							'<a href="javascript:void(0);" class="edit_btn"><img src="application/modules/Administrator/layouts/scripts/images/tools/edit.png" title="<?php echo $this->translator->translator("common_edit_title"); ?>" alt="<?php echo $this->translator->translator("common_edit_title"); ?>" border="0" /></a>'+
							'<a href="javascript:void(0);" class="save_btn"  style="display:none;" rel="'+datas.id+'"><img src="application/modules/Administrator/layouts/scripts/images/tools/save.gif" alt="<?php echo $this->translator->translator("common_save_title"); ?>" title="<?php echo $this->translator->translator("common_save_title"); ?>"  border="0"/></a><a href="javascript:void(0);" class="cancel_btn"  style="display:none;" rel="'+datas.id+'"><img src="application/modules/Administrator/layouts/scripts/images/tools/cancel.gif" alt="<?php echo $this->translator->translator("common_cancel_title"); ?>" title="<?php echo $this->translator->translator("common_cancel_title"); ?>"  border="0"/></a><input type="hidden" name="editable" value="disable" />'+
							<?php endif; ?>
					'</li>'+													
					'<li>'+
							<?php if ($this->allow('delete','formats','Newsletter')) : ?>
							'<a href="javascript:void(0);" class="delete_btn"  rel="'+datas.id+'"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator("common_delete_title"); ?>" alt="<?php echo $this->translator->translator("common_delete_title"); ?>" border="0" /></a>'+
							<?php endif; ?>	
					'</li>'+
				'</ul>';		
		
		oTable.fnAddData([
							'<input type="checkbox" name="checkbtn" id="checkbtn" value="'+datas.id+'" class="check_btn" />',
							datas.id,
							datas.e_format,
							datas.e_text,
							datas.e_date,
							row
							 ]);
		$('td', oTable.fnGetNodes()).hover( function() {		
			$(this).parents("tr:first").children('td').addClass( 'highlighted' );
		}, function() {
			$('td.highlighted').removeClass('highlighted');
		} );
		lastClassAdd(oTable);
		$('td', oTable.fnGetNodes()).parents("tr:first").parents("tbody:first").children('tr:last-child').children('td:nth-child(1)').addClass('center');
		$('td', oTable.fnGetNodes()).parents("tr:first").parents("tbody:first").children('tr:last-child').children('td:nth-child(1)').addClass('checkbox');
		$('td', oTable.fnGetNodes()).parents("tr:first").parents("tbody:first").children('tr:last-child').children('td:nth-child(2)').addClass('center');		
		$('td', oTable.fnGetNodes()).parents("tr:first").parents("tbody:first").children('tr:last-child').children('td:nth-child(3)').addClass('center');
		$('td', oTable.fnGetNodes()).parents("tr:first").parents("tbody:first").children('tr:last-child').children('td:nth-child(5)').addClass('center');
		$('td', oTable.fnGetNodes()).parents("tr:first").parents("tbody:first").children('tr:last-child').children('td:nth-child(6)').addClass('tools-list newsletter-list');	
		allFunctions();
}

function checkNonDeletedId(id,id_arr)
{
	var tmp = false;
	for(var i = 0;i < id_arr.length;i++)
	{
		if(id_arr[i] == id)
		{
			tmp = true;
			break;
		}
	}
	
	return tmp;
}

function openMsgDialog(msg)
{
	$('#dialog_container').html(msg).dialog({
				autoOpen: true,
				modal: false,
				show: 'fade',
				resizable: 'false',				
				buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
				open: function(event, ui)
					 {
						setTimeout(function() 
						{									
							if($('#' + event.target.id).dialog('isOpen'))
							{
								$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
							}
						}, 10000);
					  }
			});
}

function allFunctions()
{
	$('a.save_btn').click(function() {
			var self = this;
			var rel = $(self).attr('rel');
			
			if($(self).parents("li:first").children("input:nth-child(4)").val() == 'enable')
			{
				var e_format = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").children("input:nth-child(1)").val();
				var e_text = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").children("input:nth-child(1)").val();
				
				$.ajax({
						url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'formats', 'action'     => 'edit' ), 'adminrout',    true) ?>",
						type: 'POST',
						data: { id: rel, e_format: e_format, e_text: e_text},
						beforeSend: function(){						
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');	
							$(self).css('display','none');	
							$(self).parents("li:first").children("a:nth-child(3)").css('display','none');
							$(self).parents("li:first").children("a:nth-child(1)").css('display','inline');
							$(self).parents("li:first").children("input:nth-child(4)").val('disable');					
						 },
						success: function(response) 
						{
							//alert(response);
							var json_arr = eval("("+response+")");
							if(json_arr.status == 'ok')
							{
								$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html(e_format);
								$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html(e_text);
								$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(5)").html(json_arr.e_date);
							}
							else
							{
								$(self).css('display','');	
								$(self).parents("li:first").children("a:nth-child(3)").css('display','inline');
								$(self).parents("li:first").children("a:nth-child(1)").css('display','none');
								$(self).parents("li:first").children("input:nth-child(4)").val('enable');
								$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<input type="text" value="'+e_format+'" />');
								$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<input type="text" value="'+e_text+'" />');
								openMsgDialog(json_arr.msg);
							}						
						},
						error: function(xhr, status, error){							
							
							$(self).css('display','');	
							$(self).parents("li:first").children("a:nth-child(3)").css('display','inline');
							$(self).parents("li:first").children("a:nth-child(1)").css('display','none');
							$(self).parents("li:first").children("input:nth-child(4)").val('enable');
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<input type="text" value="'+e_format+'" />');
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<input type="text" value="'+e_text+'" />');
							
							var msg = "Error! " + xhr.status + " " + error;
							openMsgDialog(errMsgDesign(msg));
						}
					});
			}
		});
		
		$('a.edit_btn').click(function() {
			var self = this;
			if($(self).parents("li:first").children("input:nth-child(4)").val() == 'disable')
			{
				$(self).css('display','none');	
				$(self).parents("li:first").children("a:nth-child(2)").css('display','inline');
				$(self).parents("li:first").children("a:nth-child(3)").css('display','inline');
				var e_format = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").text();			
				var e_text = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").text();
				$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<input type="text" value="'+e_format+'" />');
				$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<input type="text" value="'+e_text+'" />');
				$(self).parents("li:first").children("input:nth-child(4)").val('enable');
			}
		});
		
		$('a.cancel_btn').click(function() {
			var self = this;
			if($(self).parents("li:first").children("input:nth-child(4)").val() == 'enable')
			{
				$(self).css('display','none');	
				$(self).parents("li:first").children("a:nth-child(2)").css('display','none');
				$(self).parents("li:first").children("a:nth-child(1)").css('display','inline');
				var e_format = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").children("input:nth-child(1)").val();
				var e_text = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").children("input:nth-child(1)").val();
				$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html(e_format);
				$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html(e_text);
				$(self).parents("li:first").children("input:nth-child(4)").val('disable');
			}
		});
		
		/* Get the rows which are currently selected */
		function fnGetSelected( oTableLocal )
		{
			var aReturn = new Array();
			var aTrs = oTableLocal.fnGetNodes();
			
			for ( var i=0 ; i<aTrs.length ; i++ )
			{
				if ( $(aTrs[i]).hasClass('row_selected') )
				{
					aReturn.push( aTrs[i] );
				}
			}
			return aReturn;
		}
		
		function deleteThis(self)
		{
			var arr = $(self).attr('rel').split('_');
			$.ajax({
				 url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'formats', 'action'     => 'delete' ), 'adminrout',    true) ?>",
				 type: 'POST',
				 data: { id: arr[0] },
				 beforeSend: function(){
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
					 },
				 success: function(response) 
				 {
					//alert(response);
					var json_arr = eval("("+response+")");
					if(json_arr.status == 'ok')
					{
						$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").addClass('row_selected');
						var oTables = $('#sortTable').dataTable();
						var anSelected = fnGetSelected( oTables );
						oTables.fnDeleteRow( anSelected[0] );
						lastClassAdd(oTables);
					}
					else
					{
						openMsgDialog(json_arr.msg);
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/delete.gif" title="<?php echo $this->translator->translator("common_delete_title"); ?>" border="0" />');
					}
				 }
			});
		}
		
		
		
		function deleteAll(self)
		{
			var id_str = '';
			for(var i=0;i < $('input.check_btn:checked').length;i++)
			{
				if(i == 0)
				{
					 id_str += $('input.check_btn:checked:eq('+i+')').val();
				}
				else
				{
					id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
				}
			}
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'formats', 'action'     => 'deleteall' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id_st: id_str},
					beforeSend: function(){
						$(self).html('<span class="icon loader"></span>');
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							for(var i= ($('input.check_btn:checked').length-1);i >= 0;i--)
							{									
								if(!checkNonDeletedId($('input.check_btn:checked:eq('+i+')').val(),json_arr.non_del_arr))
								{							
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").addClass('row_selected');	
								}
							}
							var oTabled = $('#sortTable').dataTable();
							var anSelected = fnGetSelected( oTabled );
							for(var k = 0; k < anSelected.length; k++)
							{
								oTabled.fnDeleteRow( anSelected[k] );
							}
							lastClassAdd(oTabled);								
						}
						else
						{							
							openMsgDialog(json_arr.msg);
						}	
						$(self).html('<span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span>');
					}
			});	
		}
	
	$('a.delete_btn').click(function() {
		var self = this;
		$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('formats_list_delete_confirm')); ?>").dialog({
			resizable: false,
			width: 400,
			height:150,
			modal: true,
			show: 'fade',
			hide: 'explode',
			buttons: {
					'<?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?>': function() {
					deleteThis(self);
					$(this).dialog('close');
				},
			'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
					$(this).dialog('close');
				}
			}
		});
		
	});	
		
	$('a.delete_all').click(function() {
		var self = this;
		
		if($('input.check_btn:checked').length > 0)
		{
			$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('formats_list_delete_confirm')); ?>").dialog({
					resizable: false,
					width: 400,
					height:150,
					modal: true,
					show: 'fade',
					hide: 'explode',
					buttons: {
							'<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>': function() {
							deleteAll(self);
							$(this).dialog('close');
						},
					'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
							$(this).dialog('close');
						}
					}
				});		
		}
		else
		{
			
			var msg = "<?php echo $this->translator->translator('format_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
	
	$('input.checkAll_btn').click(function() {
		var self = this;
		if($(self).is(':checked'))
		{		
			$('input.check_btn').attr('checked', true);
		}
		else
		{
			$('input.check_btn').attr('checked', false);
		}
	});
}
	
</script>
<div id="container">
<?php if (!$this->allow('list')) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="email-variables"><h1><?php echo $this->translator->translator('newsletter_variable_list_page_name'); ?></h1></div>
    
    <div class="button-container">
        <?php if ($this->allow('add','formats','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript:void(0);" class="add_new_dialog_btn"><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        <span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <?php  if ($this->allow('delete','formats','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<div id="button_top_bar"></div>
<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('nav_menu.phtml');  ?>
    </div>
    
    
    <div id="content-inner">
    	<div class="pagination">
        	<?php echo $this->paginationControl($this->formats_datas, 'Sliding', 'top_pagination.phtml'); ?>
        </div>
        
        <div class="chart">
			<div class="data-table">
            	<table id="sortTable" width="100%" align="center" cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <th width="3%" class="center"><input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn" /></th>
                            <th width="7%"><?php echo $this->translator->translator('newsletter_variable_list_page_id'); ?></th>
                            <th width="29%"><?php echo $this->translator->translator('newsletter_variable_list_page_var'); ?></th>														   
                   	    	<th width="33%"><?php echo $this->translator->translator('newsletter_variable_list_page_desc'); ?></th>
                            <th width="14%"><?php echo $this->translator->translator('common_date'); ?></th>
                            <th width="14%"><?php echo $this->translator->translator('common_action'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                        $j = 1;
                        foreach ($this->formats_datas as $entry): 
                            
                            if($j % 2 == 0)
                            {
                                $onmouseout = "this.bgColor='#FFFFFF';";
                                $background = '#FFFFFF';
                            }
                            else
                            {
                                $onmouseout = "this.bgColor='#F7F7F7';";
                                $background = '#F7F7F7';
                            }
                        ?>
                        <tr bgcolor="<?php echo $background; ?>" onmouseover="this.bgColor='#FCF5DD';" onmouseout="<?php echo $onmouseout; ?>">
                         	<td class="center checkbox"><input type="checkbox" name="checkbtn" id="checkbtn" value="<?php echo $this->escape($entry->id); ?>" class="check_btn" /></td>
                          	<td class="center"><?php echo $this->escape($entry->id); ?></td>
                          	<td class="center"><?php echo $this->escape($entry->e_format); ?></td>
                          	<td><?php echo $this->escape($entry->e_text); ?></td>
                          	<td class="center"><?php	echo $this->escape($entry->e_date); ?></td>
                          	<td class="tools-list newsletter-list">
                            	<ul>
                                	<li>
										<?php if ($this->allow('edit','formats','Newsletter')) : ?>                                	
                                        	<a href="javascript:void(0);" class="edit_btn"><img src="application/modules/Administrator/layouts/scripts/images/tools/edit.png" title="<?php echo $this->translator->translator('common_edit_title'); ?>" alt="<?php echo $this->translator->translator('common_edit_title'); ?>" border="0" /></a>
                                        	<a href="javascript:void(0);" class="save_btn"  style="display:none;" rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/save.gif" alt="<?php echo $this->translator->translator('common_save_title'); ?>" title="<?php echo $this->translator->translator('common_save_title'); ?>"  border="0"/></a><a href="javascript:void(0);" class="cancel_btn"  style="display:none;" rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/cancel.gif" alt="<?php echo $this->translator->translator('common_cancel_title'); ?>" title="<?php echo $this->translator->translator('common_cancel_title'); ?>"  border="0"/></a><input type="hidden" name="editable" value="disable" />
                                        <?php endif; ?>
                                    </li>
                                    <li>
										<?php if ($this->allow('delete','formats','Newsletter')) : ?>
                                        	<a href="javascript:void(0);" class="delete_btn"  rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator('common_delete_title'); ?>" alt="<?php echo $this->translator->translator('common_delete_title'); ?>" border="0" /></a>
                                        <?php endif; ?>	                      
                                   </li>
                              	</ul>
                          	</td>
                        </tr>
                        <?php 													
                           $j++;
                           endforeach;	
                        ?>
                    </tbody>
				</table>
        	</div>
		</div>
        
        <div><input type="hidden" name="tb_row" id="tb_row" value="<?php echo $j; ?>" /></div>
        
        <div class="pagination">
        	<?php echo $this->paginationControl($this->formats_datas, 'Sliding', 'pagination.phtml'); ?>
        </div>
	</div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('newsletter_variable_list_page_name'); ?></h1>
    
    <div class="button-container">
        <?php if ($this->allow('add','formats','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript:void(0);" class="add_new_dialog_btn"><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        <span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <?php  if ($this->allow('delete','formats','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('newsletter_variable_list_page_name')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>
<div id="add-format-form" title="<?php echo $this->translator->translator('newsletter_variable_add_page_name'); ?>">
    <div class="dialog-container">	
        <div class="title-container">
            <div class="email-variable-add"><h1><?php echo $this->translator->translator('newsletter_variable_add_page_name'); ?></h1></div>
            
            <div class="button-container">            
                <span class="button  ui-widget-content-1"><a href="javascript:void(0);" class="close_dialog_btn"><span class="icon close"><?php echo $this->translator->translator('common_close'); ?></span></a></span>
                <span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>            
                <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="add_variable_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
            </div>
        </div>
        
        <div class="content-container">
            <div id="generalInfo">
        		<div id="actionMessage"></div>
                <form id="formFormat" name="formFormat" method="post">
                    <fieldset class="fieldset last">
                        <legend class="legend"><?php echo $this->formatsForm->e_format->getLabel(); if($this->formatsForm->e_format->isRequired()){ ?><span class="required">*</span><?php } ?></legend>
                        <div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->formatsForm->e_format->getLabel(); if($this->formatsForm->e_format->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php $this->formatsForm->e_format->setValue('%%');				  
                                    echo $this->formatsForm->e_format; 
                                    ?>
                                    <div class="input-errors" id="e_format_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->formatsForm->e_text->getLabel(); if($this->formatsForm->e_text->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->formatsForm->e_text; ?>
                                    <div class="input-errors" id="e_text_err"></div>
                                </div>
                            </div>
                            
                        </div>
                    </fieldset>
                </form>
        	</div>
        </div>
    </div>
</div>

<div id="dialog_loader" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
</div>