<?php
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');
?>
<script type="text/javascript">
$(document).ready(function() {
	floatingbar('#floatingbar',"#button_top_bar",null);
		/****************************Sorting Table Start*********************/
	var oTable = $("#sortTable").dataTable({
				"bPaginate": false,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,
				"aaSorting": [[ 1, "asc" ]],				
				"aoColumnDefs": [ 
						{ "bSortable": false, "bSortClasses": false,  "aTargets": [ 0 ] }
					],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			}); 	
	
	$('td', oTable.fnGetNodes()).hover( function() {		
		$(this).parents("tr:first").children('td').addClass( 'highlighted' );
	}, function() {
		$('td.highlighted').removeClass('highlighted');
	} );
	
	/* Get the rows which are currently selected */
	function fnGetSelected( oTableLocal )
	{
		var aReturn = new Array();
		var aTrs = oTableLocal.fnGetNodes();
		
		for ( var i=0 ; i<aTrs.length ; i++ )
		{
			if ( $(aTrs[i]).hasClass('row_selected') )
			{
				aReturn.push( aTrs[i] );
			}
		}
		return aReturn;
	}
	lastClassAdd(oTable);
	/****************************Sorting Table End*********************/
	
		function openMsgDialog(msg)
		{
			$('#dialog_container').html(msg).dialog({
						autoOpen: true,
						modal: false,
						show: 'fade',
						resizable: 'false',				
						buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
						open: function(event, ui)
							 {
								setTimeout(function() 
								{									
									if($('#' + event.target.id).dialog('isOpen'))
									{
										$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
									}
								}, 10000);
							  }
					});
		}
		
		$('a.publish_btn').click(function() {
		var self = this;
		$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" border="0" height="16" />');
		var arr = $(self).attr('rel').split('_');
			$.ajax({
				 url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'subscribers', 'action'     => 'publish' ), 'adminrout',    true) ?>",
				 type: 'POST',
				 data: { id: arr[0], name: arr[1], paction: arr[2]},
				 success: function(response) 
				 {
					//alert(response);
					var json_arr = eval("("+response+")");
					if(json_arr.status == 'ok')
					{
						if(json_arr.un_sub == '0')
						{
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(6)").html('<?php echo $this->translator->translator("common_subscribed_language"); ?>');
							$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif"  border="0" title="<?php echo $this->translator->translator("common_unsubscribe_title"); ?>" alt="<?php echo $this->translator->translator("common_unsubscribe_title"); ?>" />').attr('rel',arr[0]+"_"+arr[1]+"_unpublish");
						}
						else
						{
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(6)").html('<?php echo $this->translator->translator("common_unsubscribed_language"); ?>');
							$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/published.gif" border="0" title="<?php echo $this->translator->translator("common_subscribe_title"); ?>" alt="<?php echo $this->translator->translator("common_subscribe_title"); ?>" />').attr('rel',arr[0]+"_"+arr[1]+"_publish");
						}
					}
					else
					{
						openMsgDialog(json_arr.msg);
					}
				 }
			});
		});
		
		$('a.save_btn').click(function() {
			var self = this;
			var rel = $(self).attr('rel');
			
			var subscriber_name = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").children("input:first").val();
			var subscriber_email = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").children("input:first").val();
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'subscribers', 'action'     => 'edit' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id: rel, name: subscriber_name, email: subscriber_email},
					beforeSend: function(){						
						$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
					 	$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');						
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							$(self).css('display','none');	
							$(self).parents("li:first").children("a:nth-child(3)").css('display','none');
							$(self).parents("li:first").children("a:first").css('display','inline');
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html(subscriber_name);
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html(subscriber_email);
						}
						else
						{
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<input type="text" value="'+subscriber_name+'" />');
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<input type="text" value="'+subscriber_email+'" />');
							openMsgDialog(json_arr.msg);
						}						
					},
						error: function(xhr, status, error){							
							
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<input type="text" value="'+subscriber_name+'" />');
							$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<input type="text" value="'+subscriber_email+'" />');
							
							var msg = "Error! " + xhr.status + " " + error;
							openMsgDialog(errMsgDesign(msg));
						}
				});
		});
		
		$('a.edit_btn').click(function() {
			var self = this;			
			$(self).css('display','none');	
			$(self).parents("li:first").children("a:nth-child(2)").css('display','inline');
			$(self).parents("li:first").children("a:nth-child(3)").css('display','inline');
			var subscriber_name = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").text();
			var subscriber_email = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").text();
			$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html('<input type="text" value="'+subscriber_name+'" />');
			$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html('<input type="text" value="'+subscriber_email+'" />');
		});
		
		$('a.cancel_btn').click(function() {
			var self = this;
			$(self).css('display','none');	
			$(self).parents("li:first").children("a:nth-child(2)").css('display','none');
			$(self).parents("li:first").children("a:first").css('display','inline');
			var subscriber_name = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").children("input:first").val();
			var subscriber_email = $(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").children("input:first").val();
			$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(3)").html(subscriber_name);
			$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").children("td:nth-child(4)").html(subscriber_email);			
		});
		
		function deleteThis(self)
		{
			var arr = $(self).attr('rel').split('_');
			$.ajax({
				 url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'subscribers', 'action'     => 'delete' ), 'adminrout',    true) ?>",
				 type: 'POST',
				 data: { id: arr[0], name: arr[1] },
				 beforeSend: function(){
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
					 },
				 success: function(response) 
				 {
					//alert(response);
					var json_arr = eval("("+response+")");
					if(json_arr.status == 'ok')
					{
						$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").addClass('row_selected');
						var oTables = $('#sortTable').dataTable();
						var anSelected = fnGetSelected( oTables );
						oTables.fnDeleteRow( anSelected[0] );
						lastClassAdd(oTables);
					}
					else
					{
						openMsgDialog(json_arr.msg);
						$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator("common_delete_title"); ?>" alt="<?php echo $this->translator->translator("common_delete_title"); ?>" border="0" />');
					}
				 }
			});
		}
		
		$('a.publish_all').click(function() {
		var self = this;
		var bigrel = $(self).attr('rel');
		if($('input.check_btn:checked').length > 0)
		{
			var id_str = '';
			for(var i=0;i < $('input.check_btn:checked').length;i++)
			{
				if(i == 0)
				{
					 id_str += $('input.check_btn:checked:eq('+i+')').val();
				}
				else
				{
					id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
				}
			}
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'subscribers', 'action'     => 'publishall' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id_st: id_str, paction: bigrel},
					beforeSend: function(){
						$(self).html('<span class="icon loader"></span>');
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							if(bigrel=='publish')
							{
								for(var i=0;i < $('input.check_btn:checked').length;i++)
								{								
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").html('<?php echo $this->translator->translator("common_subscribed_language"); ?>');
									var rel = $('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").children("ul:first").children("li:nth-child(3)").children("a:first").attr('rel');
									var rel_arr = rel.split('_');
									var new_rel = rel_arr[0]+'_'+rel_arr[1]+'_unpublish';
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").children("ul:first").children("li:nth-child(3)").children("a:first").attr('rel',new_rel);
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").children("ul:first").children("li:nth-child(3)").children("a:first").html('<img src="application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif" border="0" title="<?php echo $this->translator->translator("common_unsubscribe_title"); ?>" alt="<?php echo $this->translator->translator("common_unsubscribe_title"); ?>" />');								
								}
							}
							else
							{
								for(var i=0;i < $('input.check_btn:checked').length;i++)
								{								
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(6)").html('<?php echo $this->translator->translator("common_unsubscribed_language"); ?>');
									var rel = $('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").children("ul:first").children("li:nth-child(3)").children("a:first").attr('rel');
									var rel_arr = rel.split('_');
									var new_rel = rel_arr[0]+'_'+rel_arr[1]+'_publish';
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").children("ul:first").children("li:nth-child(3)").children("a:first").attr('rel',new_rel);
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").children("ul:first").children("li:nth-child(3)").children("a:first").html('<img src="application/modules/Administrator/layouts/scripts/images/tools/published.gif" border="0" title="<?php echo $this->translator->translator("common_subscribe_title"); ?>" alt="<?php echo $this->translator->translator("common_subscribe_title"); ?>" />');								
								}	
							}
						}
						else
						{
							openMsgDialog(json_arr.msg);
						}	
						if(bigrel=='publish')
						{	
							$(self).html('<span class="icon publish"><?php echo $this->translator->translator("common_subscribe_selected"); ?></span>');
						}
						else
						{
							$(self).html('<span class="icon unpublish"><?php echo $this->translator->translator("common_unsubscribe_selected"); ?></span>');
						}
					}
			});			
		}
		else
		{
			var msg = "<?php echo $this->translator->translator('subscriber_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
		
		function deleteAll(self)
		{
			var id_str = '';
			for(var i=0;i < $('input.check_btn:checked').length;i++)
			{
				if(i == 0)
				{
					 id_str += $('input.check_btn:checked:eq('+i+')').val();
				}
				else
				{
					id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
				}
			}
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Newsletter', 'controller' => 'subscribers', 'action'     => 'deleteall' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id_st: id_str},
					beforeSend: function(){
						$(self).html('<span class="icon loader"></span>');
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							for(var i= ($('input.check_btn:checked').length-1);i >= 0;i--)
							{									
								if(!checkNonDeletedId($('input.check_btn:checked:eq('+i+')').val(),json_arr.non_del_arr))
								{							
									$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").addClass('row_selected');							
								}
							}
							var oTabled = $('#sortTable').dataTable();
							var anSelected = fnGetSelected( oTabled );
							for(var k = 0; k < anSelected.length; k++)
							{
								oTabled.fnDeleteRow( anSelected[k] );
							}
							lastClassAdd(oTabled);	
						}
						else
						{							
							openMsgDialog(json_arr.msg);
						}	
						$(self).html('<span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span>');
					}
			});	
		}
	
	$('a.delete_btn').click(function() {
		var self = this;
		$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('subscribers_list_delete_confirm')); ?>").dialog({
			resizable: false,
			width:400,
			height:170,
			modal: true,
			show: 'fade',
			hide: 'explode',
			buttons: {
					'<?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?>': function() {
					deleteThis(self);
					$(this).dialog('close');
				},
			'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
					$(this).dialog('close');
				}
			}
		});
		
	});	
		
	$('a.delete_all').click(function() {
		var self = this;
		if($('input.check_btn:checked').length > 0)
		{
			$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('subscribers_list_delete_confirm')); ?>").dialog({
					resizable: false,
					width:400,
					height:170,
					modal: true,
					show: 'fade',
					hide: 'explode',
					buttons: {
							'<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>': function() {
							deleteAll(self);
							$(this).dialog('close');
						},
					'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
							$(this).dialog('close');
						}
					}
				});		
		}
		else
		{
			var msg = "<?php echo $this->translator->translator('subscriber_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
	
	$('input.checkAll_btn').click(function() {
		var self = this;
		if($(self).is(':checked'))
		{		
			$('input.check_btn').attr('checked', true);
		}
		else
		{
			$('input.check_btn').attr('checked', false);
		}
	});
	
	function checkNonDeletedId(id,id_arr)
	{
		var tmp = false;
		for(var i = 0;i < id_arr.length;i++)
		{
			if(id_arr[i] == id)
			{
				tmp = true;
				break;
			}
		}
		
		return tmp;
	}
	
});
	
</script>

<div id="container">
<?php if (!$this->allow('list')) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="subscribers-list"><h1><?php echo $this->translator->translator('newsletter_subscriber_list_page_name'); ?></h1></div>
    
    <div class="button-container">
        <?php if ($this->allow('add','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Newsletter','controller'=>'Templates', 'action'=>'add'));?>"><span class="icon add"><?php echo $this->translator->translator('newsletter_subscriber_list_page_button'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($this->allow('publish','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" rel="publish" class="publish_all"><span class="icon publish"><?php echo $this->translator->translator('common_subscribe_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($this->allow('publish','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" rel="unpublish" class="publish_all"><span class="icon unpublish"><?php echo $this->translator->translator('common_unsubscribe_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php  if ($this->allow('delete','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<div id="button_top_bar"></div>
<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('nav_menu.phtml');  ?>
    </div>
    
    
    
	<div id="content-inner">
    	<div class="pagination">
        	<?php echo $this->paginationControl($this->subscribers_datas, 'Sliding', 'top_pagination.phtml'); ?>
        </div>
        
        <div class="chart">
			<div class="data-table">
        		<table id="sortTable" width="100%" align="center" cellpadding="0" cellspacing="0">
                    <thead>
                        <tr>
                            <th width="4%" class="center"><input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn" /></th>
                            <th width="6%"><?php echo $this->translator->translator('newsletter_subscriber_list_page_id'); ?></th>
                            <th width="19%"><?php echo $this->translator->translator('newsletter_subscriber_list_page_sub_name'); ?></th>												   
							<th width="24%"><?php echo $this->translator->translator('newsletter_subscriber_list_page_email'); ?></th>
                            <th width="14%"><?php echo $this->translator->translator('common_date'); ?></th>
                            <th width="14%"><?php echo $this->translator->translator('common_status'); ?></th>
                            <th width="19%"><?php echo $this->translator->translator('common_action'); ?></th>
                        </tr>
                    </thead>
                	<tbody>
					<?php 
                    $j = 1;
                    foreach ($this->subscribers_datas as $entry): 
                        
                        if($j % 2 == 0)
                        {
                            $onmouseout = "this.bgColor='#FFFFFF';";
                            $background = '#FFFFFF';
                        }
                        else
                        {
                            $onmouseout = "this.bgColor='#F7F7F7';";
                            $background = '#F7F7F7';
                        }
                    ?>
                		<tr bgcolor="<?php echo $background; ?>" onmouseover="this.bgColor='#FCF5DD';" onmouseout="<?php echo $onmouseout; ?>">
                 			<td class="center checkbox"><input type="checkbox" name="checkbtn" id="checkbtn" value="<?php echo $this->escape($entry->id); ?>" class="check_btn" /></td>
                  			<td class="center"><?php echo $this->escape($entry->id); ?></td>
                  			<td><?php echo $this->escape($entry->name); ?></td>
                  			<td><?php echo $this->escape($entry->email); ?></td>
                  			<td class="center"><?php echo $this->escape($entry->s_date); ?></td>
                  			<td class="center"><?php if($this->escape($entry->un_sub) == '0'){ echo $this->translator->translator('common_subscribed_language'); }else{ echo $this->translator->translator('common_unsubscribed_language'); }  ?></td>
                  			<td class="tools-list newsletter-list">
                          		<ul>
                                	<li>
										<?php if ($this->allow('edit','subscribers','Newsletter')) : ?>
                                            <a href="javascript:void(0);" class="edit_btn"><img src="application/modules/Administrator/layouts/scripts/images/tools/edit.png" title="<?php echo $this->translator->translator('common_edit_title'); ?>" alt="<?php echo $this->translator->translator('common_edit_title'); ?>" border="0" /></a>
                                            <a href="javascript:void(0);" class="save_btn"  style="display:none;" rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/save.gif" alt="<?php echo $this->translator->translator('common_save_title'); ?>" title="<?php echo $this->translator->translator('common_save_title'); ?>"  border="0"/></a><a href="javascript:void(0);" class="cancel_btn"  style="display:none;" rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/cancel.gif" alt="<?php echo $this->translator->translator('common_cancel_title'); ?>" title="<?php echo $this->translator->translator('common_cancel_title'); ?>" border="0"/></a>
                                        <?php endif; ?>
                                    </li>
                                    <li>
										<?php if ($this->allow('delete','subscribers','Newsletter')) : ?>
                                            <a href="javascript:void(0);" class="delete_btn"  rel="<?php echo $this->escape($entry->id); ?>_<?php echo str_replace('_',' ',$this->escape($entry->name)); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator('common_delete_title'); ?>" alt="<?php echo $this->translator->translator('common_delete_title'); ?>" border="0" /></a>
                                        <?php endif; ?>	
                                    </li>
                                    <li>
										<?php if ($this->allow('publish','subscribers','Newsletter')) : ?>
                                            <a href="javascript:void(0);" class="publish_btn" rel="<?php echo $this->escape($entry->id); ?>_<?php echo str_replace('_','',$this->escape($entry->name)); ?>_<?php if($this->escape($entry->un_sub) == '0'){ ?>unpublish<?php }else{ ?>publish<?php } ?>"><?php if($this->escape($entry->un_sub) == '0'){ ?><img src="application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif"  border="0" title="<?php echo $this->translator->translator('common_unsubscribe_title'); ?>" alt="<?php echo $this->translator->translator('common_unsubscribe_title'); ?>" /><?php }else{ ?><img src="application/modules/Administrator/layouts/scripts/images/tools/published.gif"  border="0" title="<?php echo $this->translator->translator('common_subscribe_title'); ?>" alt="<?php echo $this->translator->translator('common_subscribe_title'); ?>" /><?php } ?></a>
                                        <?php endif; ?>
                                     </li>
                            	</ul>
                      		</td>
                		</tr>
                	<?php 													
                    	$j++;
                    	endforeach;	
                  	?>
               		</tbody>
				</table>
        	</div>
		</div>
        <div class="pagination">
        	<?php echo $this->paginationControl($this->subscribers_datas, 'Sliding', 'pagination.phtml'); ?>
        </div>
	</div>
</div>

<div  id="floatingbar">
	<h1><?php echo $this->translator->translator('newsletter_subscriber_list_page_name'); ?></h1>
    
    <div class="button-container">
        <?php if ($this->allow('add','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Newsletter','controller'=>'Templates', 'action'=>'add'));?>"><span class="icon add"><?php echo $this->translator->translator('newsletter_subscriber_list_page_button'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($this->allow('publish','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" rel="publish" class="publish_all"><span class="icon publish"><?php echo $this->translator->translator('common_subscribe_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($this->allow('publish','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" rel="unpublish" class="publish_all"><span class="icon unpublish"><?php echo $this->translator->translator('common_unsubscribe_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php  if ($this->allow('delete','subscribers','Newsletter')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('newsletter_subscriber_list_page_name')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>
</div>