<?php 
if($this->view_datas['meta_keywords']){ $this->headMeta()->setName('keywords',$this->view_datas['meta_keywords']);	}
if($this->view_datas['meta_desc']){ $this->headMeta()->setName('description',$this->view_datas['meta_desc']); }
$this->headTitle()->headTitle($this->view_datas['page_title'],'SET')->setSeparator(' - ')->headTitle($this->view_datas['meta_title']); 

$allow_obj = new News_View_Helper_Allow();
if (!$allow_obj->allowRule('view',null,null,$this->group_datas['role_id'])) : ?>
<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>
<table width="100%" border="1" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC" style="border-collapse:collapse;">
  <tr>
    <td width="80%" >		
		<table width="100%" border="0" cellpadding="0" cellspacing="0">
		  <tr>
			<td height="28" bgcolor="#EBEBEB" style="padding-top:5px;" class="news_title"> &nbsp;<?php echo $this->escape($this->view_datas['page_name']); ?></td>
		  </tr>
		  <tr>
		    <td>&nbsp;</td>
	      </tr>
		  <tr>
			<td class="news_post_date"> &nbsp; <?php echo $this->escape($this->view_datas['page_date']); ?></td>
		  </tr>
		  <tr>
			<td style="padding:6px;"><?php echo stripslashes($this->view_datas['page_desc']); ?></td>
		  </tr>
	  </table>	  
	  </td>
	 	 <?php
			if($this->groupInfo['category_panel'] == '1')
			{
				$categoryPanel = new News_View_Helper_CategoryPanel();				
		?>
			<td width="18%" valign="top" bgcolor="#EBEBEB">
				 
				 <div class="news_category_header" style="padding-top:10px;">&nbsp;<u><?php echo $this->translator->translator('common_category_list'); ?></u></div>
				 <div>&nbsp;</div>
				  <div style="width:140px; overflow:auto;" class="news_category">
					<?php echo $categoryPanel->getSubCategory('0',$this,$this->groupInfo['id'],null,$this->menu_id); ?>
				</div>
			</td>
		<?php
			}
		?>
  </tr>
</table>
<?php endif; ?>
