<!DOCTYPE html>
<?php $front_template = Zend_Registry::get('front_template'); $is_frontend = new Eicra_Model_DbTable_Frontend(); $license = new Zend_Session_Namespace('License'); $validation_data = $license->license_data;
$locale = Eicra_Global_Variable::getSession()->sess_lang;
$locale_arr = explode('_', $locale);
$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
?> 
<html dir="<?php echo $locale_direction; ?>" lang="<?php echo $locale_arr[0]; ?>"> 
<head>
<meta charset="utf-8">
<base href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/" /> 
<link rel="shortcut icon" href="<?php $global_conf = Zend_Registry::get('global_conf'); echo $global_conf['frontend_favicon']; ?>" />
<?php  echo $this->headMeta(); ?>
<?php echo html_entity_decode($this->headTitle(), ENT_QUOTES ,"UTF-8"); ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php
$version = new Eicra_License_Version();
echo $this->partial('head/headscript.phtml');
$auth = Zend_Auth::getInstance ();
$frontController = Zend_Controller_Front::getInstance();
$moduleName = strtolower($frontController->getRequest()->getModuleName());	
$controllerName = strtolower($frontController->getRequest()->getControllerName());
$actionName = strtolower($frontController->getRequest()->getActionName());
$acount_link = ($auth->hasIdentity ()) ? 'Dashboard' : 'Frontend-Login';
$add_url = ($auth->hasIdentity ()) ? $this->url(array('module'=> 'Property','controller'=>'Backendpro', 'action'=>'add'), 'adminrout', true)  : $this->serverUrl().$this->baseUrl().'/Frontend-Login';
?>

<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head> 
<body>
<div class="wrapper">
	<!-- Top Bar Start -->
	<div id="top-bar">    	
        <div class="container">
            <div class="user-link">
                <span class="welcome"><?php echo $this->translator->translator('header_welcome','', '', $front_template['theme_folder']).' '.$global_conf['site_name']; ?> | <a href="Frontend-Login"><?php echo $this->translator->translator('header_signin','', '', $front_template['theme_folder']); ?></a> | <a href="Registration/104"><?php echo $this->translator->translator('header_register','', '', $front_template['theme_folder']); ?></a></span>
            </div>
                
            <div class="quick-access">
                <div class="flags">
                    <?php echo $this->partial('blocks/header_language.phtml'); ?>
                </div>
        
                <div class="top-links">
                    <ul>
                        <li class="first"><a href="<?php echo $my_account; ?>"><?php echo $this->translator->translator('header_account','', '', $front_template['theme_folder']); ?></a></li>
                        <li><a href="Sign-In"><?php echo $this->translator->translator('header_login','', '', $front_template['theme_folder']); ?></a></li>
                        <li><a href="Register"><?php echo $this->translator->translator('header_agent_registration','', '', $front_template['theme_folder']); ?></a></li>
                        <li><a href="Feedback"><?php echo $this->translator->translator('header_feedback','', '', $front_template['theme_folder']); ?></a></li>
                        <li><a href="Site-Map"><?php echo $this->translator->translator('header_sitemap','', '', $front_template['theme_folder']); ?></a></li>
                        <!--<li><a href="Contact-Us"><?php //echo $this->translator->translator('header_contact','', '', $front_template['theme_folder']); ?></a></li>-->
                    </ul>
                 </div>
            </div>       
        </div>
	</div>
	<!-- Top Bar End -->

	<!-- Header Start -->
	<?php echo $this->layout()->render('header'); ?>
	<!-- Header End -->

	<!-- Main Body Start -->
	<div id="main-container">
    	<!-- Top Navigation Start-->
        <nav class="top-nav">
			<?php echo $this->partial('blocks/menu_header.phtml'); ?>
        </nav>
        <!-- Top Navigation End-->
        <?php  
			if($is_frontend->isFrontend()) 
			{
		?> 
        <!-- Banner Start-->
        <div id="banner">
        	<div class="left-bg"></div>
        	<div class="bg">
				<?php echo $this->partial('blocks/property_home_banner_search.phtml'); ?>
                <?php echo $this->partial('blocks/property_home_banner_agentSearch.phtml'); ?>
               	<?php echo $this->partial('blocks/ad_home_banner.phtml'); ?>
        	</div>
        	<div class="right-bg"></div>
        </div>
		<!-- Banner End-->
        <?php
			}
		?>
        
        <!-- Body Start-->
        <section id="main">
            <?php  
                if($is_frontend->isFrontend()) 
                {
            ?> 
            <!-- Content Start -->
            <article id="content">
                <!-- Featured Tab Start-->	
                <div id="usual1" class="usual">
                    <ul>
                      <li><a class="selected" href="#tab1"><?php echo $this->translator->translator('tab_residential_title','', '', $front_template['theme_folder']); ?></a></li>
                      <li><a class="" href="#tab2"><?php echo $this->translator->translator('tab_commercial_title','', '', $front_template['theme_folder']); ?></a></li>
                      <li><a class="" href="#tab3"><?php echo $this->translator->translator('tab_rural_title','', '', $front_template['theme_folder']); ?></a></li>
                      <li><a class="" href="#tab4"><?php echo $this->translator->translator('tab_land_title','', '', $front_template['theme_folder']); ?></a></li>
                      <li><a class="" href="#tab5"><?php echo $this->translator->translator('tab_agent_title','', '', $front_template['theme_folder']); ?></a></li>
                      <li><a class="" href="#tab6"><?php echo $this->translator->translator('tab_rent_title','', '', $front_template['theme_folder']); ?></a></li>
                    </ul>
                </div>
                <div class="usual-content">
                    <div style="display:block;" id="tab1"><?php echo $this->partial('blocks/property_home_content_residential.phtml'); ?></div>
                    <div style="display: none;" id="tab2"><?php echo $this->partial('blocks/property_home_content_commercial.phtml'); ?></div>
                    <div style="display: none;" id="tab3"><?php echo $this->partial('blocks/property_home_content_rural.phtml'); ?></div>
                    <div style="display: none;" id="tab4"><?php echo $this->partial('blocks/property_home_content_land.phtml'); ?></div>
                    <div style="display: none;" id="tab5"><?php echo $this->partial('blocks/property_home_content_agents.phtml'); ?></div>
                    <div style="display: none;" id="tab6"><?php echo $this->partial('blocks/property_home_content_rent.phtml'); ?></div>
                </div>
                    
                <script type="text/javascript">
                $("#usual1 ul").idTabs();
                </script>
                <!-- Featured Tab End-->
                
                <?php echo $this->partial('blocks/property_home_content_featured.phtml'); ?>
                <?php echo $this->partial('blocks/property_home_content_state.phtml'); ?>
                <?php echo $this->partial('blocks/property_home_content_region.phtml'); ?>
            </article>
            <!-- Content End -->
            
            <!-- Right Sidebar Start-->
            <aside id="sidebar">
                <?php echo $this->partial('blocks/gallery_home_sidebar_featured.phtml'); ?>
                <?php echo $this->partial('blocks/property_home_sidebar_recent.phtml'); ?>
                <?php echo $this->partial('blocks/news_sidebar_latest.phtml'); ?>
            </aside>
            <!-- Right Sidebar End-->
            
            <!-- Inner Layout Start -->
            <?php
                }
                else
                {
                    $body_content_class = '';
                    if(!empty($moduleName) && $actionName != 'home')
                    {
                        switch($moduleName)
                        {
                            case 'property':
                                $body_content_class = 'content-inner';
            ?>	
                <!-- Inner Side Bar Start-->
                <div id="sidebar-inner">
                    <?php echo $this->partial('blocks/property_inner_sidebar_search.phtml'); ?>
                    <?php echo $this->partial('blocks/ad_inner_leftsidebar.phtml'); ?>
                </div>
                <!-- Inner Side Bar End -->	
            <?php
                        break;
                    }
                }
            ?>
            
            <!-- Inner Layout End -->
                    
            <!-- Content Start-->
                <div id="<?php echo $body_content_class; ?>"> 
                    <?php echo $this->layout()->content; ?>
                </div>
            <!-- Content End-->					
            <?php
                }
            ?> 
        </section>
        <!-- Body End-->
	</div>
	<!-- Main Body End -->

	<!-- Footer Start -->
	<?php echo $this->layout()->render('footer'); ?>
    <!-- Footer End -->
</div>
<div class="go-top"><a href="#top" id="scroll-top"><?php echo $this->translator->translator('footer_top','', '', $front_template['theme_folder']); ?></a></div>
<?php echo $this->headScript()->setFile('application/layouts/scripts/'.$front_template['theme_folder'].'/vendor/scripts/js/scroll.js'); ?>
</body>
</html>
<?php echo $this->escape($global_conf['analytics_code']); ?>