<?php
$frontController = Zend_Controller_Front::getInstance();	
$getController = $frontController->getRequest()->getControllerName();
$getAction = $frontController->getRequest()->getActionName();
$translator = Zend_Registry::get('translator'); 
$modules_license = new Administrator_Controller_Helper_ModuleLoader();
?>

<div id="nav">
	<div class="nav-header"><div class="nav-title"><?php echo $translator->translator('gateway_menu_title'); ?></div></div>
    <div class="nav-body">
    	<ul>
        	<?php if ($this->allow('list','backendgateway','Paymentgateway')) : ?>
			<li <?php if($getAction == 'list' && strtolower($getController) == 'backendgateway'){ ?> class="gateway last"<?php }else{ ?>class="gateway last"<?php } ?>>
			<a href="<?php echo $this->url(array('module' => 'Paymentgateway','controller'=>'backendgateway', 'action'=>'list'),'adminrout',true);?>"><?php echo $translator->translator('gateway_menu1'); ?></a>
			</li>
			<?php endif; ?>
        </ul>
	</div>
</div>