<?php
$frontController = Zend_Controller_Front::getInstance();
$module = $frontController->getRequest()->getModuleName();
$controller = $frontController->getRequest()->getControllerName();
$action = $frontController->getRequest()->getActionName();
$search_field = ($frontController->getRequest()->getPost('search_field'))? $frontController->getRequest()->getPost('search_field') : $frontController->getRequest()->getParam('search_field');

if($this->last > 1)
{
$translator = Zend_Registry::get('translator');
?>

<div class="flickr-pagination-container">
		<ul id="pagination-flickr">
			<!-- First page link -->
			<?php if (isset($this->previous)): ?>
				  <li class="previous"><a href="<?php echo $this->url(array('module'=>$module,'controller' => $controller,'action' => $action,'search_field' => $search_field,'page' => $this->first),'Search/:search_field/:page',false); ?>"><?php echo $translator->translator('pagination_start'); ?></a></li>
			<?php else: ?>
					<li class="previous-off"><?php echo $translator->translator('pagination_start'); ?></li> 
			<?php endif; ?>
		
			<!-- Previous page link -->
		
			<?php if (isset($this->previous)): ?>
				  <li class="previous"><a href="<?php echo $this->url(array('module'=>$module,'controller' => $controller,'action' => $action,'search_field' => $search_field,'page' => $this->previous),'Search/:search_field/:page',false); ?>">&lt; <?php echo $translator->translator('pagination_previous'); ?></a></li>
			<?php else: ?>
				<li class="previous-off">&lt; <?php echo $translator->translator('pagination_previous'); ?></li>
			<?php endif; ?>
			<!-- Numbered page links -->
			<?php foreach ($this->pagesInRange as $page): ?>
				<?php if ($page != $this->current): ?>
					<li><a href="<?php echo $this->url(array('module'=>$module,'controller' => $controller,'action' => $action,'search_field' => $search_field,'page' => $page),'Search/:search_field/:page',false); ?>"><?php echo $page; ?></a></li>
				<?php else: ?>
					<li class="active"><?php echo $page; ?></li>
				<?php endif; ?>
			<?php endforeach; ?>
			<!-- Next page link -->
			<?php if (isset($this->next)): ?>
				  <li class="next"><a href="<?php echo $this->url(array('module'=>$module,'controller' => $controller,'action' => $action,'search_field' => $search_field,'page' => $this->next),'Search/:search_field/:page',false); ?>"><?php echo $translator->translator('pagination_next'); ?> &gt;</a></li>
			<?php else: ?>
				<li class="next-off"><?php echo $translator->translator('pagination_next'); ?> &gt;</li>
			<?php endif; ?>
			<!-- Last page link -->
			<?php if (isset($this->next)): ?>
				  <li class="next"><a href="<?php echo $this->url(array('module'=>$module,'controller' => $controller,'action' => $action,'search_field' => $search_field,'page' => $this->last),'Search/:search_field/:page',false); ?>"><?php echo $translator->translator('pagination_end'); ?></a></li>
			<?php else: ?>
				<li class="next-off"><?php echo $translator->translator('pagination_end'); ?></li>
			<?php endif; ?>
            	<li>&nbsp; <span class="current_page"><?php echo $translator->translator('pagination_Page'); ?> <?php echo $this->current; ?> <?php echo $translator->translator('pagination_of'); ?> <?php echo $this->last; ?></span></li>
		</ul>
</div>
<?php
}
?>