<?php $this->headTitle()->headTitle("Page Error 404",'SET'); ?>
<style>

.text_2{
	font-family:Arial, Helvetica, sans-serif;
	font-size:13px;
	color:#333333;
}

.header_4{
	font-family:Helvetica, Verdana, Arial, sans-serif;
	font-size:14.5pt;
	font-weight:bold;
	color:#333333;
	word-spacing:1px;
	line-height:25px;
	
}




</style>

<table width="600" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><table width="500" height="300" border="0" align="center" cellpadding="0" cellspacing="0" style="border:6px solid #FFD000; border-collapse:collapse">
      <tr>
        <td background="images/adminImages/commonImages/error_bg.jpg"><table width="500" height="300" border="1" cellpadding="0" cellspacing="0" bordercolor="#C1C1C1" style="border-collapse:collapse;">
          <tr>
            <td valign="middle"><table width="470" border="0" align="center" cellpadding="0" cellspacing="0">
              
              <tr>
                <td align="center"><img src="images/adminImages/commonImages/error_logo.gif" width="261" height="75" /></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
              </tr>
              
              <tr class="text_2">
                <td align="left"><span class="header_4">Opps, The page you are looking for doesn't exist!</span><br />
                  <br />
                  We are sorry, but we can't find the web pages you've requested. <br />
                  <br />
                  It's possible that: <br />
                  <br />
				  <ul style="padding-left:10px;">
				  	<li>The address was entered incorrectly. Check your spelling and try again.</li>
					<li>We may have either created a page and removed in or we may have just moved it to another section of our website.</li>
					<li>Please refresh your browser again. </li>
				  </ul>                  </td>
              </tr>
              
              
            </table></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>