<?php
	$frontController = Zend_Controller_Front::getInstance();
	$module = $frontController->getRequest()->getModuleName();
	$controller = $frontController->getRequest()->getControllerName();
	$action = $frontController->getRequest()->getActionName();
	$draft = $frontController->getRequest()->getParam('draft');
	$group_id = $frontController->getRequest()->getParam('group_id');
	$entry_by = $frontController->getRequest()->getParam('entry_by');
	$menu_name = $frontController->getRequest()->getParam('menu_name');
	$translator = Zend_Registry::get('translator'); 
?>

<?php echo $translator->translator('pagination_results'); ?> <?php echo $this->numbers($this->currentItemCount); ?> - <?php echo $this->numbers($this->current); ?> <?php echo $translator->translator('pagination_of'); ?> <?php echo $this->numbers($this->last); ?></td>

<div class="page-no">
	<?php if (isset($this->previous)): ?><a href="<?php echo $this->url(array('module' => $module,'controller' => $controller,'action' => $action,'draft' => $draft, 'entry_by' => $entry_by, 'group_id' => $group_id, 'menu_name' => $menu_name,'page' => $this->previous),'adminrout',true); ?>"><</a><?php else: ?><<?php endif; ?>
	<!-- Numbered page links -->
			<?php foreach ($this->pagesInRange as $page): ?>
				<?php if ($page != $this->current): ?>
					<a href="<?php echo $this->url(array('module' => $module,'controller' => $controller,'action' => $action,'draft' => $draft, 'entry_by' => $entry_by, 'group_id' => $group_id, 'menu_name' => $menu_name,'page' => $page),'adminrout',true); ?>">[<?php echo $this->numbers($page); ?>]</a>
				<?php else: ?>
					<?php echo $this->numbers($page); ?>
				<?php endif; ?>
			<?php endforeach; ?>
			<!-- Next page link -->
	<?php if (isset($this->next)): ?><a href="<?php echo $this->url(array('module' => $module,'controller' => $controller,'action' => $action,'draft' => $draft, 'entry_by' => $entry_by, 'group_id' => $group_id, 'menu_name' => $menu_name,'page' => $this->next),'adminrout',true); ?>">></a><?php else: ?>><?php endif; ?>
</div>